In [21]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 999)
pd.set_option('display.max_rows', 999)
pd.set_option("display.max_seq_items", None)

### Data Import and Sorting

In [22]:
#This should eventually get replaced by the 2025 data (or any data) from AWS
data = pd.read_csv('historical_pitches_rnn_data.csv')
data.head(-20)

,pitch_type,game_date,batter,pitcher,description,zone,stand,p_throws,balls,strikes,game_year,game_type,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,sz_top,sz_bot,game_pk,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,home_score_diff,bat_score_diff
0,FS,2025-11-01,672386,808967,hit_into_play,6.0,R,R,0,2,2025,W,665489.0,NaN,680718.0,1,11,Bot,3.13,1.50,813024,99,3,Split-Finger,4,5,4,5,-1,-1
1,FF,2025-10-25,605141,686973,foul,6.0,R,R,2,1,2025,W,NaN,681624.0,660271.0,1,8,Top,3.20,1.51,813026,55,4,4-Seam Fastball,1,3,3,1,-2,2
2,KC,2025-10-25,605141,686973,ball,14.0,R,R,1,1,2025,W,NaN,681624.0,660271.0,1,8,Top,3.14,1.52,813026,55,3,Knuckle Curve,1,3,3,1,-2,2
3,KC,2025-10-25,605141,686973,called_strike,6.0,R,R,1,0,2025,W,NaN,681624.0,660271.0,1,8,Top,2.99,1.34,813026,55,2,Knuckle Curve,1,3,3,1,-2,2
4,KC,2025-10-25,605141,686973,blocked_ball,14.0,R,R,0,0,2025,W,NaN,681624.0,660271.0,1,8,Top,2.99,1.43,813026,55,1,Knuckle Curve,1,3,3,1,-2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
723970,FF,2025-03-27,605137,554430,called_strike,3.0,L,R,0,0,2025,R,NaN,NaN,NaN,0,2,Bot,3.68,1.77,778555,10,1,4-Seam Fastball,0,0,0,0,0,0
723971,SL,2025-03-27,596146,669022,called_strike,2.0,L,L,2,2,2025,R,NaN,NaN,NaN,2,2,Top,3.23,1.60,778555,9,6,Slider,0,0,0,0,0,0
723972,FF,2025-03-27,596146,669022,foul,9.0,L,L,2,2,2025,R,NaN,NaN,NaN,2,2,Top,3.51,1.72,778555,9,5,4-Seam Fastball,0,0,0,0,0,0
723973,FF,2025-03-27,596146,669022,ball,12.0,L,L,1,2,2025,R,NaN,NaN,NaN,2,2,Top,3.31,1.66,778555,9,4,4-Seam Fastball,0,0,0,0,0,0
723974,SL,2025-03-27,596146,669022,foul,13.0,L,L,1,1,2025,R,NaN,NaN,NaN,2,2,Top,3.51,1.72,778555,9,3,Slider,0,0,0,0,0,0

In [23]:
def sort_statcast(df: pd.DataFrame) -> pd.DataFrame:
    return df.sort_values(["game_date", "game_pk", "inning", "inning_topbot", "at_bat_number", "pitch_number"], ascending=[True, True, True, False, True, True]).reset_index(drop=True)

In [24]:
data = sort_statcast(data)
data.head(20)

,pitch_type,game_date,batter,pitcher,description,zone,stand,p_throws,balls,strikes,game_year,game_type,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,sz_top,sz_bot,game_pk,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,home_score_diff,bat_score_diff
0,FF,2025-03-18,660271,684007,called_strike,12.0,L,L,0,0,2025,R,NaN,NaN,NaN,0,1,Top,3.40,1.62,778563,1,1,4-Seam Fastball,0,0,0,0,0,0
1,SL,2025-03-18,660271,684007,ball,13.0,L,L,0,1,2025,R,NaN,NaN,NaN,0,1,Top,3.40,1.62,778563,1,2,Slider,0,0,0,0,0,0
2,FF,2025-03-18,660271,684007,hit_into_play,5.0,L,L,1,1,2025,R,NaN,NaN,NaN,0,1,Top,3.40,1.62,778563,1,3,4-Seam Fastball,0,0,0,0,0,0
3,FS,2025-03-18,669242,684007,ball,13.0,R,L,0,0,2025,R,NaN,NaN,NaN,1,1,Top,3.26,1.50,778563,2,1,Split-Finger,0,0,0,0,0,0
4,FS,2025-03-18,669242,684007,swinging_strike,14.0,R,L,1,0,2025,R,NaN,NaN,NaN,1,1,Top,3.26,1.50,778563,2,2,Split-Finger,0,0,0,0,0,0
5,FF,2025-03-18,669242,684007,hit_into_play,8.0,R,L,1,1,2025,R,NaN,NaN,NaN,1,1,Top,3.26,1.50,778563,2,3,4-Seam Fastball,0,0,0,0,0,0
6,FF,2025-03-18,606192,684007,swinging_strike,5.0,R,L,0,0,2025,R,NaN,NaN,NaN,2,1,Top,3.46,1.64,778563,3,1,4-Seam Fastball,0,0,0,0,0,0
7,FF,2025-03-18,606192,684007,foul,5.0,R,L,0,1,2025,R,NaN,NaN,NaN,2,1,Top,3.46,1.64,778563,3,2,4-Seam Fastball,0,0,0,0,0,0
8,FS,2025-03-18,606192,684007,swinging_strike,14.0,R,L,0,2,2025,R,NaN,NaN,NaN,2,1,Top,3.46,1.64,778563,3,3,Split-Finger,0,0,0,0,0,0
9,FF,2025-03-18,664023,808967,ball,13.0,L,R,1,0,2025,R,NaN,NaN,NaN,0,1,Bot,3.52,1.63,778563,4,2,4-Seam Fastball,0,0,0,0,0,0
10,FF,2025-03-18,664023,808967,ball,14.0,L,R,2,0,2025,R,NaN,NaN,NaN,0,1,Bot,3.52,1.63,778563,4,3,4-Seam Fastball,0,0,0,0,0,0
11,FF,2025-03-18,664023,808967,called_strike,4.0,L,R,3,0,2025,R,NaN,NaN,NaN,0,1,Bot,3.52,1.63,778563,4,4,4-Seam Fastball,0,0,0,0,0,0
12,FF,2025-03-18,664023,808967,called_strike,7.0,L,R,3,1,2025,R,NaN,NaN,NaN,0,1,Bot,3.52,1.63,778563,4,5,4-Seam Fastball,0,0,0,0,0,0
13,FF,2025-03-18,664023,808967,ball,13.0,L,R,3,2,2025,R,NaN,NaN,NaN,0,1,Bot,3.52,1.63,778563,4,6,4-Seam Fastball,0,0,0,0,0,0
14,FF,2025-03-18,673548,808967,foul,5.0,R,R,0,0,2025,R,NaN,NaN,664023.0,0,1,Bot,3.18,1.43,778563,5,1,4-Seam Fastball,0,0,0,0,0,0
15,FS,2025-03-18,673548,808967,ball,8.0,R,R,0,1,2025,R,NaN,NaN,664023.0,0,1,Bot,3.18,1.43,778563,5,2,Split-Finger,0,0,0,0,0,0
16,SI,2025-03-18,673548,808967,hit_into_play,11.0,R,R,1,1,2025,R,NaN,NaN,664023.0,0,1,Bot,3.18,1.43,778563,5,3,Sinker,0,0,0,0,0,0
17,CU,2025-03-18,663656,808967,swinging_strike,14.0,L,R,0,0,2025,R,NaN,NaN,664023.0,1,1,Bot,3.47,1.67,778563,6,1,Curveball,0,0,0,0,0,0
18,FF,2025-03-18,663656,808967,called_strike,9.0,L,R,0,1,2025,R,NaN,NaN,664023.0,1,1,Bot,3.47,1.67,778563,6,2,4-Seam Fastball,0,0,0,0,0,0
19,FS,2025-03-18,663656,808967,hit_into_play,13.0,L,R,0,2,2025,R,NaN,NaN,664023.0,1,1,Bot,3.47,1.67,778563,6,3,Split-Finger,0,0,0,0,0,0

In [25]:
# We want to have a unique id for each plate appearance (PA)
data["pa_id"] = data["game_pk"].astype(str) + "_" + data["at_bat_number"].astype(str)

In [ ]:
# Getting rid of infrequently used pitches
pitch_remapping = {
    'SC': 'OTHER',
    'PO': 'OTHER',
    'CS': 'OTHER',
    'FA': 'OTHER',
}

data['pitch_type'] = data['pitch_type'].replace(pitch_remapping)

In [27]:
# Handling automatic balls and strikes. Some entries have a pitch type of NaN. By looking at the description of the pitch,
#   we can see this is due to pitch clock violations. This replaces the NaNs with ABS instead.
abs_remapping = {
    'automatic_ball': 'ABS',
    'automatic_strike': 'ABS',
}
data['pitch_type'] = (data['description'].map(abs_remapping).fillna(data['pitch_type']))

In [28]:
# Handling if previous pitch in sequence was ABS 
abs_label = ["ABS"]

is_abs = data["pitch_type"].isin(abs_label)
data["pitch_type_for_prev"] = data["pitch_type"].mask(is_abs)

# Track last real pitch type within each PA, will be NaN until first pitch is actually thrown
data["last_real_pitch_type"] = (data.groupby("pa_id")["pitch_type_for_prev"].ffill())

# Previous pitch type is the last real pitch but shifted 1. NaNs are now filled
data["prev_pitch_type"] = (data.groupby("pa_id")["last_real_pitch_type"].shift(1).fillna("START"))

# don't care about thse columns
data = data.drop(columns=["pitch_type_for_prev", "last_real_pitch_type"])

In [29]:
# For each plate appearance, get the length (number of pitches thrown)
data["seq_len"] = data.groupby("pa_id")["pitch_type"].transform("size")

In [30]:
data = data[data["game_type"] == 'R']
data = data[data["pitch_type"] != 'UN']

### Feature Creation

#### Rolling averages of certain stats

In [31]:
# Creating Indicator columns 
# We should have these already but im just doing this based on the statcast set so making them again. 
swing_code = ['foul_bunt', 'foul', 'hit_into_play', 'swinging_strike', 'foul_tip',
                'swinging_strike_blocked', 'missed_bunt', 'bunt_foul_tip']
whiff_code = ['swinging_strike', 'foul_tip', 'swinging_strike_blocked']

# 0 = no, 1 = yes
data['is_swing'] = data['description'].isin(swing_code)
data['is_whiff'] = data['description'].isin(whiff_code)

data["is_called_strike"] = (data["description"] == "called_strike")
data["is_ball"] = data["description"].isin(["ball", "blocked_ball"])

data['in_zone'] = (data['zone'] < 10)
data['out_zone'] = (data['zone'] > 10)

#### Game State Features

In [32]:
# Make base occupancy into bools
for base_col in ["on_1b", "on_2b", "on_3b"]:
    data[base_col] = data[base_col].notna()

# Make count a string (combining balls ans strikes)
data['count_state'] = (data['balls'].astype(int).astype(str) + "-" + data['strikes'].astype(int).astype(str))

data["score_diff_bat"] = data["bat_score"] - data["fld_score"]

data.head()

,pitch_type,game_date,batter,pitcher,description,zone,stand,p_throws,balls,strikes,game_year,game_type,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,sz_top,sz_bot,game_pk,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,home_score_diff,bat_score_diff,pa_id,prev_pitch_type,seq_len,is_swing,is_whiff,is_called_strike,is_ball,in_zone,out_zone,count_state,score_diff_bat
0,FF,2025-03-18,660271,684007,called_strike,12.0,L,L,0,0,2025,R,False,False,False,0,1,Top,3.40,1.62,778563,1,1,4-Seam Fastball,0,0,0,0,0,0,778563_1,START,3,False,False,True,False,False,True,0-0,0
1,SL,2025-03-18,660271,684007,ball,13.0,L,L,0,1,2025,R,False,False,False,0,1,Top,3.40,1.62,778563,1,2,Slider,0,0,0,0,0,0,778563_1,FF,3,False,False,False,True,False,True,0-1,0
2,FF,2025-03-18,660271,684007,hit_into_play,5.0,L,L,1,1,2025,R,False,False,False,0,1,Top,3.40,1.62,778563,1,3,4-Seam Fastball,0,0,0,0,0,0,778563_1,SL,3,True,False,False,False,True,False,1-1,0
3,FS,2025-03-18,669242,684007,ball,13.0,R,L,0,0,2025,R,False,False,False,1,1,Top,3.26,1.50,778563,2,1,Split-Finger,0,0,0,0,0,0,778563_2,START,3,False,False,False,True,False,True,0-0,0
4,FS,2025-03-18,669242,684007,swinging_strike,14.0,R,L,1,0,2025,R,False,False,False,1,1,Top,3.26,1.50,778563,2,2,Split-Finger,0,0,0,0,0,0,778563_2,FS,3,True,True,False,False,False,True,1-0,0

#### Dropping unneccessary columns

In [33]:
drop_cols = [
    "player_name", "events", "sv_id", "umpire", "des",
    "spin_dir", "spin_rate_deprecated", "break_angle_deprecated", "break_length_deprecated", "game_type", "home_team", "away_team", "type", "hit_location", "bb_type", 
    "hc_x", "hc_y", "tfs_deprecated", "tfs_zulu_deprecated", "hit_distance_sc", "launch_speed", "launch_angle", "effective_speed", 
    "fielder_2", "fielder_3", "fielder_4",	"fielder_5", "fielder_6", "fielder_7", "fielder_8",	"fielder_9",
    "estimated_ba_using_speedangle", "estimated_woba_using_speedangle", "estimated_slg_using_speedangle", "woba_value", "woba_denom", "babip_value", "iso_value", "launch_speed_angle",
    "if_fielding_alignment", "of_fielding_alignment", "delta_home_win_exp", "hyper_speed", "bat_speed", "swing_length", "home_win_exp", "bat_win_exp", 
    "age_pit_legacy", "age_bat_legacy", "age_pit", "age_bat", "attack_angle", "attack_direction", "swing_path_tilt", 
    "intercept_ball_minus_batter_pos_x_inches", "intercept_ball_minus_batter_pos_y_inches", "Unnamed: 0", 
    "delta_run_exp", "delta_pitcher_run_exp", "batter_days_until_next_game", "api_break_z_with_gravity", "api_break_x_arm", "api_break_x_batter_in", "batter_days_until_next_game",
    "pitcher_days_until_next_game", "batter_days_since_prev_game", "pitcher_days_since_prev_game", "n_priorpa_thisgame_player_at_bat", "n_thruorder_pitcher", 
    # "is_whiff", "is_called_strike", "is_ball", "is_zone", "zone",
    "vx0", "vy0", "vz0", "ax", "ay", "az", "pfx_x", "pfx_z", "release_spin_rate", "spin_axis", "arm_angle", "plate_x", "plate_z", 'release_speed', 'release_pos_x', 'release_pos_z', 'release_extension', 'release_pos_y',
    # "at_bat_number", "pitch_number", "batter", "pitcher", "game_pk", "game_date", "description", "pitch_name", "game_year", "description"
    'post_away_score','post_home_score', 'post_bat_score', 'post_fld_score',
]
    
clean_data = data.drop(columns=[c for c in drop_cols], errors="ignore")
clean_data.head()

clean_data.info()

<class 'pandas.DataFrame'>
Index: 709898 entries, 0 to 709898
Data columns (total 40 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   pitch_type        709898 non-null  str
 1   game_date         709898 non-null  str
 2   batter            709898 non-null  int64
 3   pitcher           709898 non-null  int64
 4   description       709898 non-null  str
 5   zone              709895 non-null  float64
 6   stand             709898 non-null  str
 7   p_throws          709898 non-null  str
 8   balls             709898 non-null  int64
 9   strikes           709898 non-null  int64
 10  game_year         709898 non-null  int64
 11  on_3b             709898 non-null  bool
 12  on_2b             709898 non-null  bool
 13  on_1b             709898 non-null  bool
 14  outs_when_up      709898 non-null  int64
 15  inning            709898 non-null  int64
 16  inning_topbot     709898 non-null  str
 17  sz_top            709895 non-null  float64
 18  sz_bot            709895 non-null  float64
 19  game_pk           709898 non-null  int64
 20  at_bat_number     709898 non-null  int64
 21  pitch_number      709898 non-null  int64
 22  pitch_name        709898 non-null  str
 23  home_score        709898 non-null  int64
 24  away_score        709898 non-null  int64
 25  bat_score         709898 non-null  int64
 26  fld_score         709898 non-null  int64
 27  home_score_diff   709898 non-null  int64
 28  bat_score_diff    709898 non-null  int64
 29  pa_id             709898 non-null  str
 30  prev_pitch_type   709898 non-null  str
 31  seq_len           709898 non-null  int64
 32  is_swing          709898 non-null  bool
 33  is_whiff          709898 non-null  bool
 34  is_called_strike  709898 non-null  bool
 35  is_ball           709898 non-null  bool
 36  in_zone           709898 non-null  bool
 37  out_zone          709898 non-null  bool
 38  count_state       709898 non-null  str
 39  score_diff_bat    709898 non-null  int64
dtypes: bool(9), float64(3), int64(18), str(10)
memory usage: 179.4 MB

In [34]:
clean_data.to_csv('rnn_data.csv', index=False)