In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import pybaseball as pyb

pd.set_option('display.max_columns', 999)
pd.set_option('display.max_rows', 999)
pd.set_option("display.max_seq_items", None)

### Data Import and Sorting

In [3]:
data = pd.read_csv('data2025.csv')
data

,Unnamed: 0,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,des,game_type,stand,p_throws,home_team,away_team,type,hit_location,bb_type,balls,strikes,game_year,pfx_x,pfx_z,plate_x,plate_z,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,hc_x,hc_y,tfs_deprecated,tfs_zulu_deprecated,umpire,sv_id,vx0,vy0,vz0,ax,ay,az,sz_top,sz_bot,hit_distance_sc,launch_speed,launch_angle,effective_speed,release_spin_rate,release_extension,game_pk,fielder_2,fielder_3,fielder_4,fielder_5,fielder_6,fielder_7,fielder_8,fielder_9,release_pos_y,estimated_ba_using_speedangle,estimated_woba_using_speedangle,woba_value,woba_denom,babip_value,iso_value,launch_speed_angle,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp,bat_speed,swing_length,estimated_slg_using_speedangle,delta_pitcher_run_exp,hyper_speed,home_score_diff,bat_score_diff,home_win_exp,bat_win_exp,age_pit_legacy,age_bat_legacy,age_pit,age_bat,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,2019,FF,2025-09-28,95.7,-2.15,5.21,"Weissert, Greg",678009,669711,field_out,hit_into_play,NaN,NaN,NaN,NaN,1.0,Parker Meadows flies out to left fielder Jarre...,R,L,R,BOS,DET,X,7.0,fly_ball,0,0,2025,-0.71,0.93,-0.40,3.08,NaN,700242.0,628451.0,2,9,Top,96.06,86.56,NaN,NaN,NaN,NaN,6.169368,-139.262184,-2.088523,-10.601017,31.025947,-19.832498,3.45,1.69,290.0,83.8,37.0,94.9,2370.0,5.8,776151,657136,663993,666152,681987,686765,680776,678882,677800,54.67,0.010,0.009,0.0,1.0,0.0,0.0,3.0,74,1,4-Seam Fastball,4,3,3,4,3,4,3,4,Infield shade,Strategic,226.0,0.146,-0.282,69.0,7.1,0.016,0.282,88.0,1,-1,0.854,0.146,30,25,30,26,1,4,2.0,1.0,4.0,2.0,1.56,0.71,-0.71,20.9,5.991833,-1.319512,28.782516,41.559201,30.599805
1,2098,FF,2025-09-28,95.1,-1.91,5.10,"Weissert, Greg",668670,669711,strikeout,called_strike,NaN,NaN,NaN,NaN,6.0,Jake Rogers called out on strikes.,R,R,R,BOS,DET,S,2.0,NaN,0,2,2025,-0.93,0.93,0.57,2.59,NaN,700242.0,628451.0,1,9,Top,NaN,NaN,NaN,NaN,NaN,NaN,8.617368,-138.217784,-3.023825,-13.845463,30.454633,-19.764496,3.37,1.53,NaN,NaN,NaN,95.6,2309.0,6.6,776151,657136,663993,666152,681987,686765,680776,678882,677800,53.86,NaN,0.000,0.0,1.0,0.0,0.0,NaN,73,4,4-Seam Fastball,4,3,3,4,3,4,3,4,Standard,Standard,229.0,0.093,-0.160,NaN,NaN,NaN,0.160,NaN,1,-1,0.761,0.239,30,30,30,30,1,3,2.0,9.0,4.0,9.0,1.59,0.93,0.93,20.5,NaN,NaN,NaN,NaN,NaN
2,2180,FF,2025-09-28,95.4,-1.99,5.22,"Weissert, Greg",668670,669711,NaN,foul,NaN,NaN,NaN,NaN,2.0,Foul,R,R,R,BOS,DET,S,NaN,NaN,0,2,2025,-0.85,1.14,0.06,3.30,NaN,700242.0,628451.0,1,9,Top,NaN,NaN,NaN,NaN,NaN,NaN,7.213709,-138.740928,-1.962713,-12.545880,30.045431,-17.188392,3.47,1.60,246.0,80.3,45.0,94.6,2314.0,5.8,776151,657136,663993,666152,681987,686765,680776,678882,677800,54.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73,3,4-Seam Fastball,4,3,3,4,3,4,3,4,Standard,Standard,211.0,0.000,0.000,63.5,6.2,NaN,0.000,88.0,1,-1,0.761,0.239,30,30,30,30,1,3,2.0,9.0,4.0,9.0,1.36,0.85,0.85,22.9,2.871131,31.805044,22.266527,37.478847,15.582717
3,2259,SL,2025-09-28,84.8,-2.33,4.72,"Weissert, Greg",668670,669711,NaN,swinging_strike,NaN,NaN,NaN,NaN,5.0,Swinging Strike,R,R,R,BOS,DET,S,NaN,NaN,0,1,2025,0.32,0.62,0.14,2.59,NaN,700242.0,628451.0,1,9,Top,NaN,NaN,NaN,NaN,NaN,NaN,5.156934,-123.459684,0.134447,2.225813,24.458800,-26.088975,3.47,1.60,NaN,NaN,NaN,85.0,2528.0,6.4,776151,657136,663993,666152,681987,686765,680776,678882,677800,54.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73,2,Slider,4,3,3,4,3,4,3,4,Standard,Standard,106.0,0.029,-0.053,72.9,7.6,NaN,0.053,NaN,1,-1,0.732,0.268,30,30,30,30,1,3,2.0,9.0,4.0,9.0,2.55,-0.32,-0.32,12.3,13.785410,4.081390,32.414181,38.011685,27.083341
4,2360,SL,2025-09-28,85.3,-2.26,4.85,"Weissert, Greg",668670,669711,NaN,called_strike,NaN,NaN,NaN,NaN,12.0,Called Strike,R,R,R,BOS,DET,S,NaN,NaN,0,0,2025,0.52,0.41,0.93,2.57,NaN,700242.0,628451.0,1,9,Top,NaN,NaN,NaN,NaN,NaN,NaN,6.425252,-124.208027,0.091855,4.131948,23.966198,-28.183591,3.40,1.59,NaN,NaN,NaN,85.0,2548.0,5.9,776151,657136,663993,666152,681987,686765,680776,678882,677800,54.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73,1,Slider,4,3,3,4,3,4,3,4,Standard,Standard,98.0,0.021,-0.033,NaN,NaN,NaN,0.033,NaN,1,-1,0.711,0.289,30,30,30,30,1,3,2.0,9.0,4.0,9.0,2.71,-0.52,-0.52,15.8,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742075,2932,FS,2025-03-18,83.1,2.67,5.42,"Imanaga, Shota",669242,684007,NaN,swinging_strike,NaN,NaN,NaN,NaN,14.0,Swinging Strike,R,R,L,CHC,LAD,S,NaN,NaN,1,0,2025,1.32,0.45,1.08,1.89,NaN,NaN,NaN,1,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-6.209890,-120.937164,-2.480434,14.181419,23.802721,-27.501698,3.26,1.50,NaN,NaN,NaN,82.8,1190.0,6.1,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,Split-Finger,0,0,0,0,0,0,0,0,Standard,Standard,125.0,0.003,-0.049,69.2,8.7,NaN,0.049,NaN,0,0,0.520,0.480,31,30,32,30,1,0,NaN,NaN,11.0,1.0,2.85,1.32,-1.32,35.1,16.805059,-27.234241,23.369440,49.218242,45.254212
742076,3084,FS,2025-03-18,83.2,2.79,5.49,"Imanaga, Shota",669242,684007,NaN,ball,NaN,NaN,NaN,NaN,13.0,Ball,R,R,L,CHC,LAD,B,NaN,NaN,0,0,2025,1.10,0.67,-0.66,0.91,NaN,NaN,NaN,1,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-10.074865,-120.651047,-5.315742,12.763199,23.680576,-24.772585,3.26,1.50,NaN,NaN,NaN,83.1,1133.0,6.5,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1,Split-Finger,0,0,0,0,0,0,0,0,Standard,Standard,128.0,-0.002,0.039,NaN,NaN,NaN,-0.039,NaN,0,0,0.522,0.478,31,30,32,30,1,0,NaN,NaN,11.0,1.0,2.65,1.10,-1.10,37.8,NaN,NaN,NaN,NaN,NaN
742077,3206,FF,2025-03-18,93.1,2.45,5.46,"Imanaga, Shota",660271,684007,field_out,hit_into_play,NaN,NaN,NaN,NaN,5.0,"Shohei Ohtani grounds out, second baseman Jon ...",R,L,L,CHC,LAD,X,4.0,ground_ball,1,1,2025,1.06,1.66,-0.14,2.61,NaN,NaN,NaN,0,1,Top,148.47,156.14,NaN,NaN,NaN,NaN,-8.947780,-135.121062,-5.039529,15.106256,34.552133,-11.020534,3.40,1.62,7.0,76.0,-20.0,92.1,2664.0,6.2,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.29,0.071,0.070,0.0,1.0,0.0,0.0,2.0,1,3,4-Seam Fastball,0,0,0,0,0,0,0,0,Infield shade,Standard,147.0,0.021,-0.251,81.6,8.7,0.095,0.251,88.0,0,0,0.501,0.499,31,30,32,31,1,0,NaN,NaN,11.0,1.0,1.02,1.06,1.06,39.3,21.212752,-17.459294,32.491473,43.002657,37.667497
742078,3281,SL,2025-03-18,83.1,2.88,5.31,"Imanaga, Shota",660271,684007,NaN,ball,NaN,NaN,NaN,NaN,13.0,Ball,R,L,L,CHC,LAD,B,NaN,NaN,0,1,2025,-0.24,0.34,-1.80,-1.29,NaN,NaN,NaN,0,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-10.170850,-120.308756,-9.171457,-0.277878,23.719025,-27.207681,3.40,1.62,NaN,NaN,NaN,82.3,2734.0,6.1,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,Slider,0,0,0,0,0,0,0,0,Infield shade,Standard,292.0,-0.002,0.031,NaN,NaN,NaN,-0.031,NaN,0,0,0.503,0.497,31,30,32,31,1,0,NaN,NaN,11.0,1.0,3.00,-0.24,-0.24,31.0,NaN,NaN,NaN,NaN,NaN
742079,3383,FF,2025-03-18,92.5,2.38,5.54,"Imanaga, Shota",660271,684007,NaN,called_strike,NaN,NaN,NaN,NaN,12.0,Called Strike,R,L,L,CHC,LAD,S,NaN,NaN,0,0,2025,0.95,1.51,0.21,3.62,NaN,NaN,NaN,0,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-7.595896,-134.402105,-2.247584,13.295462,34.344626,-13.838992,3.40,1.62,NaN,NaN,NaN,91.6,2685.0,6.3,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,4-Seam Fastball,0,0,0,0,0,0,0,0,Infield shade,Standard,150.0,0.003,-0.039,NaN,NaN,NaN,0.039,NaN,0,0,0.500,0.500,31,30,32,31,1,0,NaN,NaN,11.0,1.0,1.21,0.95,0.95,38.9,NaN,NaN,NaN,NaN,NaN

In [4]:
data.sample(5)

,Unnamed: 0,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,des,game_type,stand,p_throws,home_team,away_team,type,hit_location,bb_type,balls,strikes,game_year,pfx_x,pfx_z,plate_x,plate_z,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,hc_x,hc_y,tfs_deprecated,tfs_zulu_deprecated,umpire,sv_id,vx0,vy0,vz0,ax,ay,az,sz_top,sz_bot,hit_distance_sc,launch_speed,launch_angle,effective_speed,release_spin_rate,release_extension,game_pk,fielder_2,fielder_3,fielder_4,fielder_5,fielder_6,fielder_7,fielder_8,fielder_9,release_pos_y,estimated_ba_using_speedangle,estimated_woba_using_speedangle,woba_value,woba_denom,babip_value,iso_value,launch_speed_angle,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp,bat_speed,swing_length,estimated_slg_using_speedangle,delta_pitcher_run_exp,hyper_speed,home_score_diff,bat_score_diff,home_win_exp,bat_win_exp,age_pit_legacy,age_bat_legacy,age_pit,age_bat,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
517142,495,FF,2025-05-16,93.1,-2.57,5.33,"Flaherty, Jack",666182,656427,NaN,called_strike,NaN,NaN,NaN,NaN,7.0,Called Strike,R,R,R,TOR,DET,S,NaN,NaN,0,1,2025,-0.18,1.19,-0.59,1.98,NaN,NaN,NaN,1,6,Bot,NaN,NaN,NaN,NaN,NaN,NaN,5.505631,-135.408324,-5.471385,-3.362987,29.329909,-16.581035,3.73,1.64,NaN,NaN,NaN,93.7,2166.0,6.6,777906,693307,679529,650402,656716,700242,682985,595879,681481,53.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48,2,4-Seam Fastball,0,4,0,4,4,0,0,4,Standard,Standard,210.0,-0.002,-0.052,NaN,NaN,NaN,0.052,NaN,-4,-4,0.076,0.076,29,27,30,27,3,2,6.0,1.0,6.0,1.0,1.44,0.18,0.18,28.7,NaN,NaN,NaN,NaN,NaN
615408,1952,FF,2025-04-21,92.6,-2.83,4.67,"Anderson, Grant",664774,681982,NaN,ball,NaN,NaN,NaN,NaN,12.0,Ball,R,L,R,SF,MIL,B,NaN,NaN,0,2,2025,-0.98,1.07,0.18,4.14,NaN,NaN,NaN,1,6,Bot,NaN,NaN,NaN,NaN,NaN,NaN,9.819995,-134.507792,2.127084,-14.045602,28.555104,-19.906718,3.17,1.50,NaN,NaN,NaN,92.7,2337.0,6.4,778226,661388,656555,668930,702332,687401,686555,686217,694192,54.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49,3,4-Seam Fastball,2,2,2,2,2,2,2,2,Strategic,Standard,244.0,0.003,0.017,NaN,NaN,NaN,-0.017,NaN,0,0,0.533,0.533,28,31,28,31,1,2,2.0,2.0,1.0,2.0,1.60,0.98,-0.98,4.6,NaN,NaN,NaN,NaN,NaN
305559,1090,FC,2025-07-10,91.0,-1.90,6.00,"Vásquez, Randy",677950,681190,NaN,ball,NaN,NaN,NaN,NaN,7.0,Ball,R,L,R,SD,AZ,B,NaN,NaN,2,1,2025,0.08,1.14,-0.28,1.55,NaN,NaN,664983.0,0,3,Top,NaN,NaN,NaN,NaN,NaN,NaN,3.889804,-132.317233,-7.633267,0.010483,29.702248,-17.329968,2.83,1.36,NaN,NaN,NaN,90.3,2476.0,6.0,777158,455117,650333,630105,578428,593428,657757,701538,665487,54.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,4,Cutter,0,0,0,0,0,0,0,0,Infield shade,Standard,206.0,-0.018,0.116,NaN,NaN,NaN,-0.116,NaN,0,0,0.453,0.547,26,25,27,25,1,0,6.0,1.0,11.0,1.0,1.63,-0.08,0.08,35.4,NaN,NaN,NaN,NaN,NaN
276352,2302,SI,2025-07-21,96.6,0.43,6.42,"Ashby, Aaron",810938,676879,NaN,ball,NaN,NaN,NaN,NaN,14.0,Ball,R,R,L,SEA,MIL,B,NaN,NaN,1,2,2025,1.08,0.47,0.34,0.42,NaN,NaN,NaN,1,8,Bot,NaN,NaN,NaN,NaN,NaN,NaN,-2.635740,-140.388743,-11.310398,14.925851,29.148221,-23.759122,3.45,1.53,NaN,NaN,NaN,95.2,2074.0,5.3,777050,661388,683734,668930,678011,687401,686555,663368,694192,55.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59,4,Sinker,0,6,0,6,6,0,0,6,Standard,Standard,143.0,0.000,0.048,NaN,NaN,NaN,-0.048,NaN,-6,-6,0.006,0.006,27,24,27,25,1,2,2.0,2.0,4.0,1.0,1.96,1.08,-1.08,48.1,NaN,NaN,NaN,NaN,NaN
270708,637,SL,2025-07-22,84.4,-1.97,5.87,"Keller, Mitch",690993,656605,field_out,hit_into_play,NaN,NaN,NaN,NaN,5.0,Colt Keith lines out sharply to right fielder ...,R,L,R,PIT,DET,X,9.0,line_drive,0,0,2025,0.27,-0.14,0.06,2.30,NaN,NaN,NaN,0,5,Top,173.98,83.12,NaN,NaN,NaN,NaN,4.250816,-122.863225,-1.664623,1.826820,24.832465,-33.441593,3.27,1.54,310.0,100.6,21.0,85.5,2441.0,7.0,777044,680779,687462,693304,663647,643396,502054,665833,672744,53.51,0.320385,0.506615,0.0,1.0,0.0,0.0,5.0,42,1,Slider,5,3,3,5,3,5,3,5,Infield shade,Standard,88.0,0.029,-0.259,74.5,7.1,0.926923,0.259,100.6,2,-2,0.751,0.249,29,23,29,24,3,2,9.0,1.0,6.0,1.0,3.34,-0.27,0.27,38.7,12.085557,1.312934,35.11408,36.862052,34.321147

In [5]:
data = data[data["game_type"] == 'R']
data = data[data["pitch_type"] != 'UN']

In [6]:
def sort_statcast(df: pd.DataFrame) -> pd.DataFrame:
    return df.sort_values(["game_date", "game_pk", "inning", "inning_topbot", "at_bat_number", "pitch_number"], ascending=[True, True, True, False, True, True]).reset_index(drop=True)

In [7]:
data = sort_statcast(data)
data.head(20)

,Unnamed: 0,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,des,game_type,stand,p_throws,home_team,away_team,type,hit_location,bb_type,balls,strikes,game_year,pfx_x,pfx_z,plate_x,plate_z,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,hc_x,hc_y,tfs_deprecated,tfs_zulu_deprecated,umpire,sv_id,vx0,vy0,vz0,ax,ay,az,sz_top,sz_bot,hit_distance_sc,launch_speed,launch_angle,effective_speed,release_spin_rate,release_extension,game_pk,fielder_2,fielder_3,fielder_4,fielder_5,fielder_6,fielder_7,fielder_8,fielder_9,release_pos_y,estimated_ba_using_speedangle,estimated_woba_using_speedangle,woba_value,woba_denom,babip_value,iso_value,launch_speed_angle,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp,bat_speed,swing_length,estimated_slg_using_speedangle,delta_pitcher_run_exp,hyper_speed,home_score_diff,bat_score_diff,home_win_exp,bat_win_exp,age_pit_legacy,age_bat_legacy,age_pit,age_bat,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,3383,FF,2025-03-18,92.5,2.38,5.54,"Imanaga, Shota",660271,684007,NaN,called_strike,NaN,NaN,NaN,NaN,12.0,Called Strike,R,L,L,CHC,LAD,S,NaN,NaN,0,0,2025,0.95,1.51,0.21,3.62,NaN,NaN,NaN,0,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-7.595896,-134.402105,-2.247584,13.295462,34.344626,-13.838992,3.40,1.62,NaN,NaN,NaN,91.6,2685.0,6.3,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,4-Seam Fastball,0,0,0,0,0,0,0,0,Infield shade,Standard,150.0,0.003,-0.039,NaN,NaN,NaN,0.039,NaN,0,0,0.500,0.500,31,30,32,31,1,0,NaN,NaN,11.0,1.0,1.21,0.95,0.95,38.9,NaN,NaN,NaN,NaN,NaN
1,3281,SL,2025-03-18,83.1,2.88,5.31,"Imanaga, Shota",660271,684007,NaN,ball,NaN,NaN,NaN,NaN,13.0,Ball,R,L,L,CHC,LAD,B,NaN,NaN,0,1,2025,-0.24,0.34,-1.80,-1.29,NaN,NaN,NaN,0,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-10.170850,-120.308756,-9.171457,-0.277878,23.719025,-27.207681,3.40,1.62,NaN,NaN,NaN,82.3,2734.0,6.1,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,Slider,0,0,0,0,0,0,0,0,Infield shade,Standard,292.0,-0.002,0.031,NaN,NaN,NaN,-0.031,NaN,0,0,0.503,0.497,31,30,32,31,1,0,NaN,NaN,11.0,1.0,3.00,-0.24,-0.24,31.0,NaN,NaN,NaN,NaN,NaN
2,3206,FF,2025-03-18,93.1,2.45,5.46,"Imanaga, Shota",660271,684007,field_out,hit_into_play,NaN,NaN,NaN,NaN,5.0,"Shohei Ohtani grounds out, second baseman Jon ...",R,L,L,CHC,LAD,X,4.0,ground_ball,1,1,2025,1.06,1.66,-0.14,2.61,NaN,NaN,NaN,0,1,Top,148.47,156.14,NaN,NaN,NaN,NaN,-8.947780,-135.121062,-5.039529,15.106256,34.552133,-11.020534,3.40,1.62,7.0,76.0,-20.0,92.1,2664.0,6.2,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.29,0.071,0.070000,0.0,1.0,0.0,0.0,2.0,1,3,4-Seam Fastball,0,0,0,0,0,0,0,0,Infield shade,Standard,147.0,0.021,-0.251,81.6,8.7,0.095,0.251,88.0,0,0,0.501,0.499,31,30,32,31,1,0,NaN,NaN,11.0,1.0,1.02,1.06,1.06,39.3,21.212752,-17.459294,32.491473,43.002657,37.667497
3,3084,FS,2025-03-18,83.2,2.79,5.49,"Imanaga, Shota",669242,684007,NaN,ball,NaN,NaN,NaN,NaN,13.0,Ball,R,R,L,CHC,LAD,B,NaN,NaN,0,0,2025,1.10,0.67,-0.66,0.91,NaN,NaN,NaN,1,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-10.074865,-120.651047,-5.315742,12.763199,23.680576,-24.772585,3.26,1.50,NaN,NaN,NaN,83.1,1133.0,6.5,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1,Split-Finger,0,0,0,0,0,0,0,0,Standard,Standard,128.0,-0.002,0.039,NaN,NaN,NaN,-0.039,NaN,0,0,0.522,0.478,31,30,32,30,1,0,NaN,NaN,11.0,1.0,2.65,1.10,-1.10,37.8,NaN,NaN,NaN,NaN,NaN
4,2932,FS,2025-03-18,83.1,2.67,5.42,"Imanaga, Shota",669242,684007,NaN,swinging_strike,NaN,NaN,NaN,NaN,14.0,Swinging Strike,R,R,L,CHC,LAD,S,NaN,NaN,1,0,2025,1.32,0.45,1.08,1.89,NaN,NaN,NaN,1,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-6.209890,-120.937164,-2.480434,14.181419,23.802721,-27.501698,3.26,1.50,NaN,NaN,NaN,82.8,1190.0,6.1,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,Split-Finger,0,0,0,0,0,0,0,0,Standard,Standard,125.0,0.003,-0.049,69.2,8.7,NaN,0.049,NaN,0,0,0.520,0.480,31,30,32,30,1,0,NaN,NaN,11.0,1.0,2.85,1.32,-1.32,35.1,16.805059,-27.234241,23.369440,49.218242,45.254212
5,2835,FF,2025-03-18,93.7,2.49,5.40,"Imanaga, Shota",669242,684007,field_out,hit_into_play,NaN,NaN,NaN,NaN,8.0,Tommy Edman pops out to first baseman Michael ...,R,R,L,CHC,LAD,X,3.0,popup,1,1,2025,1.12,1.48,0.26,1.88,NaN,NaN,NaN,1,1,Top,149.48,158.68,NaN,NaN,NaN,NaN,-8.216263,-135.976415,-6.513181,15.789006,34.027490,-12.532752,3.26,1.50,91.0,72.5,72.0,93.0,2584.0,6.4,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.13,0.001,0.000000,0.0,1.0,0.0,0.0,3.0,2,3,4-Seam Fastball,0,0,0,0,0,0,0,0,Standard,Standard,142.0,0.015,-0.244,75.3,8.3,0.001,0.244,88.0,0,0,0.523,0.477,31,30,32,30,1,0,NaN,NaN,11.0,1.0,1.16,1.12,-1.12,37.1,20.374566,-17.237369,30.560790,39.991412,38.239523
6,2722,FF,2025-03-18,93.1,2.47,5.48,"Imanaga, Shota",606192,684007,NaN,swinging_strike,NaN,NaN,NaN,NaN,5.0,Swinging Strike,R,R,L,CHC,LAD,S,NaN,NaN,0,0,2025,1.32,1.51,0.13,2.38,NaN,NaN,NaN,2,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-8.869103,-135.158624,-5.378506,18.238519,33.939733,-12.668487,3.46,1.64,NaN,NaN,NaN,92.3,2594.0,6.3,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,4-Seam Fastball,0,0,0,0,0,0,0,0,Standard,Standard,150.0,0.002,-0.043,76.8,8.2,NaN,0.043,NaN,0,0,0.538,0.462,31,32,32,33,1,0,NaN,NaN,11.0,1.0,1.16,1.32,-1.32,38.8,11.750656,2.324586,37.588060,38.981820,24.708089
7,2644,FF,2025-03-18,93.7,2.40,5.50,"Imanaga, Shota",606192,684007,NaN,foul,NaN,NaN,NaN,NaN,5.0,Foul,R,R,L,CHC,LAD,S,NaN,NaN,0,1,2025,1.25,1.60,0.18,2.67,NaN,NaN,NaN,2,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-8.496924,-136.024314,-5.001192,17.536198,34.236508,-11.473892,3.46,1.64,191.0,77.4,58.0,92.9,2612.0,6.3,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,4-Seam Fastball,0,0,0,0,0,0,0,0,Standard,Standard,141.0,0.001,-0.057,70.0,7.7,NaN,0.057,88.0,0,0,0.540,0.460,31,32,32,33,1,0,NaN,NaN,11.0,1.0,1.04,1.25,-1.25,39.0,4.151287,7.548171,36.264482,39.010707,23.729355
8,2532,FS,2025-03-18,84.6,2.82,5.49,"Imanaga, Shota",606192,684007,strikeout,swinging_strike,NaN,NaN,NaN,NaN,14.0,Teoscar Hernández strikes out swinging.,R,R,L,CHC,LAD,S,2.0,NaN,0,2,2025,1.03,0.54,0.74,1.39,NaN,NaN,NaN,2,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-6.883300,-122.937868,-4.225067,11.823357,26.000228,-26.074770,3.46,1.64,NaN,NaN,NaN,84.4,1230.0,6.4,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.14,NaN,0.000000,0.0,1.0,0.0,0.0,NaN,3,3,Split-Finger,0,0,0,0,0,0,0,0,Standard,Standard,120.0,0.007,-0.160,72.1,9.1,NaN,0.160,NaN,0,0,0.541,0.459,31,32,32,33,1,0,NaN,NaN,11.0,1.0,2.67,1.03,-1.03,35.2,22.974691,-17.250583,35.118780,46.970661,42.170992
9,3495,NaN,2025-03-18,NaN,NaN,NaN,"Yamamoto, Yoshinobu",664023,808967,NaN,automatic_ball,NaN,NaN,NaN,NaN,NaN,Automatic Ball - Pitcher Pitch Timer Violation,R,L,R,CHC,LAD,B,NaN,NaN,0,0,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,Bot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,778563,669257,571771,669242,571970,500743,624424,681624,606192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,NaN,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0.003,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0.548,0.548,26,30,27,31,1,0,NaN,NaN,10.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,3481,FF,2025-03-18,97.3,-1.79,5.55,"Yamamoto, Yoshinobu",664023,808967,NaN,ball,NaN,NaN,NaN,NaN,13.0,Ball,R,L,R,CHC,LAD,B,NaN,NaN,1,0,2025,-0.80,1.44,-0.71,1.01,NaN,NaN,NaN,0,1,Bot,NaN,NaN,NaN,NaN,NaN,NaN,4.728174,-141.247679,-9.897276,-11.819712,35.674865,-10.766848,3.52,1.63,NaN,NaN,NaN,97.1,2282.0,6.5,778563,669257,571771,669242,571970,500743,624424,681624,606192,53.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,2,4-Seam Fastball,0,0,0,0,0,0,0,0,Standard,Standard,215.0,0.007,0.077,NaN,NaN,NaN,-0.077,NaN,0,0,0.551,0.551,26,30,27,31,1,0,NaN,NaN,10.0,1.0,1.00,0.80,-0.80,43.6,NaN,NaN,NaN,NaN,NaN
11,3261,FF,2025-03-18,97.6,-1.69,5.55,"Yamamoto, Yoshinobu",664023,808967,NaN,ball,NaN,NaN,NaN,NaN,14.0,Ball,R,L,R,CHC,LAD,B,NaN,NaN,2,0,2025,-0.74,1.46,0.54,1.51,NaN,NaN,NaN,0,1,Bot,NaN,NaN,NaN,NaN,NaN,NaN,7.722399,-141.756027,-8.699865,-11.835724,34.035763,-10.606540,3.52,1.63,NaN,NaN,NaN,97.5,2338.0,6.5,778563,669257,571771,669242,571970,500743,624424,681624,606192,54.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,3,4-Seam Fastball,0,0,0,0,0,0,0,0,Standard,Standard,215.0,0.011,0.152,NaN,NaN,NaN,-0.152,NaN,0,0,0.558,0.558,26,30,27,31,1,0,NaN,NaN,10.0,1.0,0.95,0.74,-0.74,45.3,NaN,NaN,NaN,NaN,NaN
12,3142,FF,2025-03-18,97.1,-1.84,5.44,"Yamamoto, Yoshinobu",664023,808967,NaN,called_strike,NaN,NaN,NaN,NaN,4.0,Called Strike,R,L,R,CHC,LAD,S,NaN,NaN,3,0,2025,-0.84,1.38,-0.44,2.37,NaN,NaN,NaN,0,1,Bot,NaN,NaN,NaN,NaN,NaN,NaN,5.684697,-141.168465,-5.816495,-12.542878,33.986497,-12.651435,3.52,1.63,NaN,NaN,NaN,97.3,2298.0,6.6,778563,669257,571771,669242,571970,500743,624424,681624,606192,53.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,4-Seam Fastball,0,0,0,0,0,0,0,0,Standard,Standard,218.0,-0.007,-0.090,NaN,NaN,NaN,0.090,NaN,0,0,0.569,0.569,26,30,27,31,1,0,NaN,NaN,10.0,1.0,1.06,0.84,-0.84,40.6,NaN,NaN,NaN,NaN,NaN
13,3113,FF,2025-03-18,97.9,-1.69,5.48,"Yamamoto, Yoshinobu",664023,808967,NaN,called_strike,NaN,NaN,NaN,NaN,7.0,Called Strike,R,L,R,CHC,LAD,S,NaN,NaN,3,1,2025,-0.88,1.56,-0.59,1.59,NaN,NaN,NaN,0,1,Bot,NaN,NaN,NaN,NaN,NaN,NaN,5.020716,-142.203781,-8.599614,-13.090016,34.457035,-9.228758,3.52,1.63,NaN,NaN,NaN,98.0,2302.0,6.6,778563,669257,571771,669242,571970,500743,624424,681624,606192,53.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,5,4-Seam Fastball,0,0,0,0,0,0,0,0,Strategic,Standard,213.0,-0.009,-0.094,NaN,NaN,NaN,0.094,NaN,0,0,0.562,0.562,26,30,27,31,1,0,NaN,NaN,10.0,1.0,0.84,0.88,-0.88,44.2,NaN,NaN,NaN,NaN,NaN
14,3016,FF,2025-03-18,98.1,-1.82,5.43,"Yamamoto, Yoshinobu",664023,808967,walk,ball,NaN,NaN,NaN,NaN,13.0,Ian Happ walks.,R,L,R,CHC,LAD,B,NaN,NaN,3,2,2025,-0.80,1.53,-1.34,2.35,NaN,NaN,NaN,0,1,Bot,NaN,NaN,NaN,NaN,NaN,NaN,3.155703,-142.710354,-6.354500,-11.663386,35.781491,-9.979798,3.52,1.63,NaN,NaN,NaN,97.9,2249.0,6.4,778563,669257,571771,669242,571970,500743,624424,681624,606192,54.09,NaN,0.691497,0.7,1.0,0.0,0.0,NaN,4,6,4-Seam Fastball,0,0,0,0,0,0,0,0,Infield shade,Standard,215.0,0.030,0.356,NaN,NaN,NaN,-0.356,NaN,0,0,0.553,0.553,26,30,27,31,1,0,NaN,NaN,10.0,1.0,0.85,0.80,-0.80,42.0,NaN,NaN,NaN,NaN,NaN
15,2910,FF,2025-03-18,97.3,-1.84,5.40,"Yamamoto, Yoshinobu",673548,808967,NaN,foul,NaN,NaN,NaN,NaN,5.0,Foul,R,R,R,CHC,LAD,S,NaN,NaN,0,0,2025,-0.86,1.48,-0.12,2.32,NaN,NaN,664023.0,0,1,Bot,NaN,NaN,NaN,NaN,NaN,NaN,6.603810,-141.484531,-6.112500,-13.107125,33.535385,-11.147713,3.18,1.43,197.0,76.7,21.0,97.5,2213.0,6.5,778563,669257,571771,669242,571970,500743,624424,681624,606192,53.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,1,4-Seam Fastball,0,0,0,0,0,0,0,0,Standard,Standard,218.0,-0.005,-0.043,83.8,7.3,NaN,0.043,88.0,0,0,0.583,0.583,26,30,27,31,1,0,NaN,NaN,10.0,1.0,0.94,0.86,0.86,39.4,-1.474041,3.867345,37.476247,35.189334,24.685215
16,2786,FS,2025-03-18,92.4,-1.78,5.44,"Yamamoto, Yoshinobu",673548,808967,NaN,ball,NaN,NaN,NaN,NaN,8.0,Ball,R,R,R,CHC,LAD,B,NaN,NaN,0,1,2025,-0.83,0.17,-0.05,1.31,NaN,NaN,664023.0,0,1,Bot,NaN,NaN,NaN,NaN,NaN,NaN,6.256504,-134.364320,-5.052431,-11.465246,30.521738,-29.229569,3.18,1.43,NaN,NaN,NaN,92.9,1586.0,6.7,778563,669257,571771,669242,571970,500743,624424,681624,606192,53.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,2,Split-Finger,0,0,0,0,0,0,0,0,Standard,Standard,237.0,0.003,0.034,NaN,NaN,NaN,-0.034,NaN,0,0,0.578,0.578,26,30,27,31,1,0,NaN,NaN,10.0,1.0,2.52,0.83,0.83,39.9,NaN,NaN,NaN,NaN,NaN
17,2683,SI,2025-03-18,96.7,-1.75,5.46,"Yamamoto, Yoshinobu",673548,808967,field_out,hit_into_play,NaN,NaN,NaN,NaN,11.0,Seiya Suzuki lines out to shortstop Miguel Rojas.,R,R,R,CHC,LAD,X,6.0,line_drive,1,1,2025,-1.09,1.20,-1.24,3.03,NaN,NaN,664023.0,0,1,Bot,121.09,138.34,NaN,NaN,NaN,NaN,3.859323,-140.657414,-3.612051,-15.312364,35.155453,-15.677598,3.18,1.43,157.0,55.0,31.0,96.7,2243.0,6.6,778563,669257,571771,669242,571970,500743,624424,681624,606192,53.94,0.276,0.248000,0.0,1.0,0.0,0.0,1.0,5,3,Sinker,0,0,0,0,0,0,0,0,Standard,Standard,217.0,-0.030,-0.234,64.8,6.3,0.276,0.234,88.0,0,0,0.581,0.581,26,30,27,31,1,0,NaN,NaN,10.0,1.0,1.26,1.09,1.09,40.3,5.695259,-4.941211,28.636723,21.870419,26.058279
18,2581,CU,2025-03-18,79.0,-1.65,5.56,"Yamamoto, Yoshinobu",663656,808967,NaN,swinging_strike,NaN,NaN,NaN,NaN,14.0,Swinging Strike,R,L,R,CHC,LAD,S,NaN,NaN,0,0,2025,1.19,-1.48,0.56,1.44,NaN,NaN,664023.0,1,1,Bot,NaN,NaN,NaN,NaN,NaN,NaN,2.606658,-114.865161,0.819130,9.722807,27.136424,-45.453805,3.47,1.67,NaN,NaN,NaN,78.7,2965.0,6.8,778563,669257,571771,669242,571970,500743,624424,681624,606192,53.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,1,Curveball,0,0,0,0,0,0,0,0,Standard,Standard,38.0,-0.004,-0.040,73.0,8.8,NaN,0.040,NaN,0,0,0.551,0.551,26,28,27,28,1,0,NaN,NaN,10.0,1.0,5.22,-1.19,1.19,48.3,33.219427,-35.755692,36.877094,33.372749,48.118165
19,2474,FF,2025-03-18,97.4,-1.73,5.46,"Yamamoto, Yoshinobu",663656,808967,NaN,called_strike,NaN,NaN,NaN,NaN,9.0,Called Strike,R,L,R,CHC,LAD,S,NaN,NaN,0,1,2025,-0.78,1.39,0.33,1.78,NaN,NaN,664023.0,1,1,Bot,NaN,NaN,NaN,NaN,NaN,NaN,7.325272,-141.438421,-7.508473,-12.171368,34.754400,-11.985802,3.47,1.67,NaN,NaN,NaN,97.3,2281.0,6.5,778563,669257,571771,669242,571970,500743,624424,681624,606192,53.97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,2,4-Seam Fastball,0,0,0,0,0,0,0,0,Standard,Standard,219.0,-0.006,-0.047,NaN,NaN,NaN,0.047,NaN,0,0,0.547,0.547,26,28,27,28,1,0,NaN,NaN,10.0,1.0,1.04,0.78,-0.78,42.0,NaN,NaN,NaN,NaN,NaN

### Feature Creation

#### Rolling averages of certain stats

In [8]:
# Creating Indicator columns 
# We should have these already but im just doing this based on the statcast set so making them again. 
swing_code = ['foul_bunt', 'foul', 'hit_into_play', 'swinging_strike', 'foul_tip',
                'swinging_strike_blocked', 'missed_bunt', 'bunt_foul_tip']
whiff_code = ['swinging_strike', 'foul_tip', 'swinging_strike_blocked']

# 0 = no, 1 = yes
data['is_swing'] = data['description'].isin(swing_code)
data['is_whiff'] = data['description'].isin(whiff_code)

data["is_called_strike"] = (data["description"] == "called_strike")
data["is_ball"] = data["description"].isin(["ball", "blocked_ball"])

data['in_zone'] = (data['zone'] < 10)
data['out_zone'] = (data['zone'] > 10)

#### Game State Features

In [10]:
# Make base occupancy into bools
for base_col in ["on_1b", "on_2b", "on_3b"]:
    data[base_col] = data[base_col].notna()

# Make count a string (combining balls ans strikes)
data['count_state'] = (data['balls'].astype(int).astype(str) + "-" + data['strikes'].astype(int).astype(str))

data["score_diff_bat"] = data["bat_score"] - data["fld_score"]

data.head()

,Unnamed: 0,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,des,game_type,stand,p_throws,home_team,away_team,type,hit_location,bb_type,balls,strikes,game_year,pfx_x,pfx_z,plate_x,plate_z,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,hc_x,hc_y,tfs_deprecated,tfs_zulu_deprecated,umpire,sv_id,vx0,vy0,vz0,ax,ay,az,sz_top,sz_bot,hit_distance_sc,launch_speed,launch_angle,effective_speed,release_spin_rate,release_extension,game_pk,fielder_2,fielder_3,fielder_4,fielder_5,fielder_6,fielder_7,fielder_8,fielder_9,release_pos_y,estimated_ba_using_speedangle,estimated_woba_using_speedangle,woba_value,woba_denom,babip_value,iso_value,launch_speed_angle,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp,bat_speed,swing_length,estimated_slg_using_speedangle,delta_pitcher_run_exp,hyper_speed,home_score_diff,bat_score_diff,home_win_exp,bat_win_exp,age_pit_legacy,age_bat_legacy,age_pit,age_bat,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches,is_swing,is_whiff,is_called_strike,is_ball,in_zone,out_zone,count_state,score_diff_bat
0,3383,FF,2025-03-18,92.5,2.38,5.54,"Imanaga, Shota",660271,684007,NaN,called_strike,NaN,NaN,NaN,NaN,12.0,Called Strike,R,L,L,CHC,LAD,S,NaN,NaN,0,0,2025,0.95,1.51,0.21,3.62,False,False,False,0,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-7.595896,-134.402105,-2.247584,13.295462,34.344626,-13.838992,3.40,1.62,NaN,NaN,NaN,91.6,2685.0,6.3,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,4-Seam Fastball,0,0,0,0,0,0,0,0,Infield shade,Standard,150.0,0.003,-0.039,NaN,NaN,NaN,0.039,NaN,0,0,0.500,0.500,31,30,32,31,1,0,NaN,NaN,11.0,1.0,1.21,0.95,0.95,38.9,NaN,NaN,NaN,NaN,NaN,False,False,True,False,False,True,0-0,0
1,3281,SL,2025-03-18,83.1,2.88,5.31,"Imanaga, Shota",660271,684007,NaN,ball,NaN,NaN,NaN,NaN,13.0,Ball,R,L,L,CHC,LAD,B,NaN,NaN,0,1,2025,-0.24,0.34,-1.80,-1.29,False,False,False,0,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-10.170850,-120.308756,-9.171457,-0.277878,23.719025,-27.207681,3.40,1.62,NaN,NaN,NaN,82.3,2734.0,6.1,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,Slider,0,0,0,0,0,0,0,0,Infield shade,Standard,292.0,-0.002,0.031,NaN,NaN,NaN,-0.031,NaN,0,0,0.503,0.497,31,30,32,31,1,0,NaN,NaN,11.0,1.0,3.00,-0.24,-0.24,31.0,NaN,NaN,NaN,NaN,NaN,False,False,False,True,False,True,0-1,0
2,3206,FF,2025-03-18,93.1,2.45,5.46,"Imanaga, Shota",660271,684007,field_out,hit_into_play,NaN,NaN,NaN,NaN,5.0,"Shohei Ohtani grounds out, second baseman Jon ...",R,L,L,CHC,LAD,X,4.0,ground_ball,1,1,2025,1.06,1.66,-0.14,2.61,False,False,False,0,1,Top,148.47,156.14,NaN,NaN,NaN,NaN,-8.947780,-135.121062,-5.039529,15.106256,34.552133,-11.020534,3.40,1.62,7.0,76.0,-20.0,92.1,2664.0,6.2,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.29,0.071,0.07,0.0,1.0,0.0,0.0,2.0,1,3,4-Seam Fastball,0,0,0,0,0,0,0,0,Infield shade,Standard,147.0,0.021,-0.251,81.6,8.7,0.095,0.251,88.0,0,0,0.501,0.499,31,30,32,31,1,0,NaN,NaN,11.0,1.0,1.02,1.06,1.06,39.3,21.212752,-17.459294,32.491473,43.002657,37.667497,True,False,False,False,True,False,1-1,0
3,3084,FS,2025-03-18,83.2,2.79,5.49,"Imanaga, Shota",669242,684007,NaN,ball,NaN,NaN,NaN,NaN,13.0,Ball,R,R,L,CHC,LAD,B,NaN,NaN,0,0,2025,1.10,0.67,-0.66,0.91,False,False,False,1,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-10.074865,-120.651047,-5.315742,12.763199,23.680576,-24.772585,3.26,1.50,NaN,NaN,NaN,83.1,1133.0,6.5,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1,Split-Finger,0,0,0,0,0,0,0,0,Standard,Standard,128.0,-0.002,0.039,NaN,NaN,NaN,-0.039,NaN,0,0,0.522,0.478,31,30,32,30,1,0,NaN,NaN,11.0,1.0,2.65,1.10,-1.10,37.8,NaN,NaN,NaN,NaN,NaN,False,False,False,True,False,True,0-0,0
4,2932,FS,2025-03-18,83.1,2.67,5.42,"Imanaga, Shota",669242,684007,NaN,swinging_strike,NaN,NaN,NaN,NaN,14.0,Swinging Strike,R,R,L,CHC,LAD,S,NaN,NaN,1,0,2025,1.32,0.45,1.08,1.89,False,False,False,1,1,Top,NaN,NaN,NaN,NaN,NaN,NaN,-6.209890,-120.937164,-2.480434,14.181419,23.802721,-27.501698,3.26,1.50,NaN,NaN,NaN,82.8,1190.0,6.1,778563,665804,683737,542932,807713,621020,664023,691718,663656,54.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,Split-Finger,0,0,0,0,0,0,0,0,Standard,Standard,125.0,0.003,-0.049,69.2,8.7,NaN,0.049,NaN,0,0,0.520,0.480,31,30,32,30,1,0,NaN,NaN,11.0,1.0,2.85,1.32,-1.32,35.1,16.805059,-27.234241,23.369440,49.218242,45.254212,True,True,False,False,False,True,1-0,0

#### Dropping unneccessary columns

In [11]:
drop_cols = [
    "player_name", "events", "sv_id", "umpire", "des",
    "spin_dir", "spin_rate_deprecated", "break_angle_deprecated", "break_length_deprecated", "game_type", "home_team", "away_team", "type", "hit_location", "bb_type", 
    "hc_x", "hc_y", "tfs_deprecated", "tfs_zulu_deprecated", "hit_distance_sc", "launch_speed", "launch_angle", "effective_speed", 
    "fielder_2", "fielder_3", "fielder_4",	"fielder_5", "fielder_6", "fielder_7", "fielder_8",	"fielder_9",
    "estimated_ba_using_speedangle", "estimated_woba_using_speedangle", "estimated_slg_using_speedangle", "woba_value", "woba_denom", "babip_value", "iso_value", "launch_speed_angle",
    "if_fielding_alignment", "of_fielding_alignment", "delta_home_win_exp", "hyper_speed", "bat_speed", "swing_length", "home_win_exp", "bat_win_exp", 
    "age_pit_legacy", "age_bat_legacy", "age_pit", "age_bat", "attack_angle", "attack_direction", "swing_path_tilt", 
    "intercept_ball_minus_batter_pos_x_inches", "intercept_ball_minus_batter_pos_y_inches", "Unnamed: 0", 
    "delta_run_exp", "delta_pitcher_run_exp", "batter_days_until_next_game", "api_break_z_with_gravity", "api_break_x_arm", "api_break_x_batter_in", "batter_days_until_next_game",
    "pitcher_days_until_next_game", "batter_days_since_prev_game", "pitcher_days_since_prev_game", "n_priorpa_thisgame_player_at_bat", "n_thruorder_pitcher", 
    # "is_whiff", "is_called_strike", "is_ball", "is_zone", "zone",
    "vx0", "vy0", "vz0", "ax", "ay", "az", "pfx_x", "pfx_z", "release_spin_rate", "spin_axis", "arm_angle", "plate_x", "plate_z", 'release_speed', 'release_pos_x', 'release_pos_z', 'release_extension', 'release_pos_y',
    # "at_bat_number", "pitch_number", "batter", "pitcher", "game_pk", "game_date", "description", "pitch_name", "game_year", "description"
    'post_away_score','post_home_score', 'post_bat_score', 'post_fld_score',
]
    
clean_data = data.drop(columns=[c for c in drop_cols], errors="ignore")
clean_data.head()

clean_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 712525 entries, 0 to 712524
Data columns (total 37 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   pitch_type        709905 non-null  object
 1   game_date         712525 non-null  object
 2   batter            712525 non-null  int64
 3   pitcher           712525 non-null  int64
 4   description       712525 non-null  object
 5   zone              709962 non-null  float64
 6   stand             712525 non-null  object
 7   p_throws          712525 non-null  object
 8   balls             712525 non-null  int64
 9   strikes           712525 non-null  int64
 10  game_year         712525 non-null  int64
 11  on_3b             712525 non-null  bool
 12  on_2b             712525 non-null  bool
 13  on_1b             712525 non-null  bool
 14  outs_when_up      712525 non-null  int64
 15  inning            712525 non-null  int64
 16  inning_topbot     712525 non-null  object
 17  sz_top            709962 non-null  float64
 18  sz_bot            709962 non-null  float64
 19  game_pk           712525 non-null  int64
 20  at_bat_number     712525 non-null  int64
 21  pitch_number      712525 non-null  int64
 22  pitch_name        709905 non-null  object
 23  home_score        712525 non-null  int64
 24  away_score        712525 non-null  int64
 25  bat_score         712525 non-null  int64
 26  fld_score         712525 non-null  int64
 27  home_score_diff   712525 non-null  int64
 28  bat_score_diff    712525 non-null  int64
 29  is_swing          712525 non-null  bool
 30  is_whiff          712525 non-null  bool
 31  is_called_strike  712525 non-null  bool
 32  is_ball           712525 non-null  bool
 33  in_zone           712525 non-null  bool
 34  out_zone          712525 non-null  bool
 35  count_state       712525 non-null  object
 36  score_diff_bat    712525 non-null  int64
dtypes: bool(9), float64(3), int64(17), object(8)
memory usage: 158.3+ MB

In [12]:
clean_data.to_csv('model_data25.csv', index=False)